### ISSUE TITLE
serverless version pinned to 2.15.0

### ISSUE THREAD

**Issue by omichowdhury** [seed-run/serverless-seed#1]
The `package.json` lists serverless@2.15.0, but I'm using serverless@2.19.0

Adding a yarn resolution to force 2.19.0 works, but causes an warning because this version is outside of the semver range

**Comment by jayair** [comment]
Are you listing the serverless version in your `package.json`?

**Comment by omichowdhury** [comment]
No, I'm not.

When I added serverless-seed, yarn added serverless it to my `yarn.lock` file, which seed then started using to deploy and breaking (because my `serverless.yml` files specify `frameworkVersion: '=2.19.0'`

**Comment by jayair** [comment]
Yeah starting, Serverless v2, it'll use the locally installed version. But it's designed a bit poorly and ends up using the version that any dependency has installed. In this case, the Seed plugin. But you should pin it to the version that you want.

https://www.serverless.com/blog/serverless-framework-v2

**Comment by omichowdhury** [comment]
Cool, I added the serverless version and tried an incremental lambda deployment, build time went from 3:38 to 1:27 🎉
